linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gosimple

linters-settings:
  errcheck:
    exclude-functions:
      - fmt.Fprintf
      - fmt.Fprintln
      - fmt.Printf
      - (io.Closer).Close

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
    - path: cmd/marmot-eval/
      linters:
        - errcheck
